env:
  global:
  - AWS_DEFAULT_REGION=ap-northeast-1
  - AWS_VPC_ID=vpc-4d790e28
  - APP_NAME=parti-auth
  - APP_ENV_NAME=parti-auth-pr
  - APP_S3BUCKET=parti-auth
  - APP_IAM_ROLE=arn:aws:iam::453285904053:instance-profile/aws-elasticbeanstalk-ec2-role
  - APP_KEY_PAIR=parti-tokyo
  - APP_SECURITY_GROUPS=ec2-parti-auth
  - AUTH_UI_REPO=partixyz/auth-ui
  - AUTH_API_REPO=partixyz/auth-api
  - AUTH_UI_PORT=8080
  - AUTH_API_PORT=3030
  - secure: GE2HwarsbHZb8Lh9hqlwip1O5D0aDG3sTuFT1XOV14gB8PTE7epv5GHZL7covajzeMwPc/kkrrqlttatKS6dyWqNTl/I2H7xuivEluvzXDfjgCm9olFvj7M9JZ0M0/eeaU5+SnHsCUAHZE3Lq+QZ+JtMF4uvh1jtmHjtaDuh0dJ1fo1RCD06wR+e4fBOVDNC1hDKc5JjCDMdU1VwTDgZRt737SO5JDiOhP7F58G61W/N31bNCsGF7H98uQjAgLIJVL9mjbQbcuDQd2KtnSVTDkbPsJkvFQa98ldDWYO2tbKajUw5m4c85CqsAqxhY7Bx3NBtbYCofg6JwCb/fWnbAyW9TwyURtkHd6+nZxKxbXtyWKK8f17JsgwTa8nAcRrSJ+FIUEFKtwqrxobyONqgTIwZoLDXYd38iHoY2Kbd7hDkk7VP3H4Ar3X7wVj6O+tUo5m5yGSB4Bc9E7li84UO+R8gibvO+lcSkgqbhpmymt/AKYlNHEVmrYSYqhM3F7YbeSZKsZSt6sSgOGbST+WyzC+tzEIOENlXab4/MWgf6biiUfpAEYzBdY1IKE9hdJ6DCmFIDe4x3tM33mNCNSzel6kdTK+EgL1iebogMUk/yUfIAMTyW6Gdou3aTnDmTLK7TM5s0ML3PUKm3ykNsLEh83nawzrg4FZHeJSdoNrrEAo=
  - secure: s5w/oF18I0CHuqA8ib50zd5Pa7Jddh1UzSeQNDZpFmr1VsvbgCicZDyGtP1kLonKv4epsPdCBOmn7ndn898g6pf4gpI575JxSo56UfCMy0fA0WqGen/D4tv6mpLWUIuN/JTmsdCIVRldmu+hZnXLb3vYimoiNmBFv/T/BDZd9yISEyzvcFmw6a6HGjsW4u9ESSpnJ/j56vp4lEkjQZ/1wLRCtHq4gDKrsJWmQhDdnHPVK3w2EptypF3T/TWQKVtQ6ivNZX31p4LFiMNXcHZosgV6TcFC82kTH9y7Qg5P3exasTgUeT5+WersNuD7kbrYPYPHSVpawXPaZ/w3pWrTBrpV20oTxX5315pZ1Xz4SVPj8i03N8yJkSJDQ7l8E/PqBGVpOANGB3i/hqzYIvI2rI1czHIdwBf6iDC/75syQr+ge84XTuhacE5OdG5YnAUyqcPvsSDJnsff2Uj4KPRpA3ls1iTbXAlV57M5uzXS4hlpxqcGIRxnX1utYyCJWc2ywNxJBxHk1JTkgeZ+IfSZqfVn5ik2TK32mJSgJ+bmdTO8F/75BJNfp93cd0FJTkdMk71Vv/aboM4mG7y/YmvXniUkwSFY11UV+WQ60998Qenqo1NZJZWeRw4aaAJxNj3FDAsRcVxPDY+lVw31vjGEnSo5icSIgysO+TPgtI8Q4L8=
  - secure: owSHQkSBHvsJf/AXkRMFVw3Rj4IjPx3Il8t+anQTZnCDd7D0WMvQRlQ3BD0dE0uqqrFGx9irw2LXlvzLiSJvZYx8qwbFKghPzFcoYHIDdWzeValleASScs/aS0TWfntA0byaPFzXCoOyAlYQxbRNSwvhU8Rnfx7PK+yexqdh/7G7YZwUksaTrdKmuhHD8EVHyJueZD2WNM8cgZam93utO6iiAxRQn4hp9pdK6Eug85/XJaB1EfyIHHbgXawx460v3+edDeZQjtzpNhq/PNa83QAkb3p9ND7zkrQ/hsFfLqou7Qudv7nNjDdttt0rJBfdZYNCaMUy7q4ZYfYUbAMTK8djxaVoMgdc51twg9QKW+YYCXzi0Xgn/vxUMlalXMqK9p6Tu0LZEIWr22xUeSKMNdN3g3TjdklfUehh004CclHwQp8ssmlYLGePJ722kYFLV4pz8Nu4YsnLCbwwiYCW0ZRSLflTs+0tZF+4V1Xz1FlwIq+LReXYJfIUM87kK4zTzulVVZwqoMYaKn6xbKvh4zqRfqz4hOX9HkJeXWGBAdYk2uWk+MjgvRB9hc/G1CHNqr60KNK2/ZPRPM1HiFpSnIsq7UQjvxh+iyKO3yuMQBbTLKvSbRz8OIX/J0300VSbIqpWxUXIfpqqA7Lw19Di3Ky7TYQlQPvXktbB/tk+PtI=
  - secure: STRby5WGulWdcKMMf5arcR4XB0xRYckwIzjBH0xxLnFqPtvOYxug2ldzxr+9IbX4nno33jUCAe++Z9iTEHTDznq4mEvO79I49dtIU7OClK2Z9oD3zhPiW7DGD8hrzGofc4dQqgFw1ENXAybrF2B5dzqGlZqMepHJyFWeE4f1Am5Orkxk1sDKWdiMFJjg4/3fhGTkus6zWYp4VGLjP7Rx9WnSeOkSxk0ZM8iT6vCR+OsYY4A1x/CtyHQQ2kYSuoOU45uOb7b0DzWUNideFvxvPEgQfnViSHCxHCbqSYe+7CDMl8oXhKRQiffcp6+PPP01nkg5wYYKIqlt66ye0XNb9yxkgdaLSiTqJWhm3REeGRHeoq1MGS+t5pXNO4UrX2Nbw4mimAG6bjfnGYUykhPkF7Hz5e30SErFBUXEGe537DK2nKiE3TcZjb9fLwyV2ZTbrG2jSsI6Jj9FsKVE2pEtXq/XNbLuF83p3zjtTZL8YBhNQcPNdEhdqK9JGG4ssc391aVYlBfs8wJQ3fF2KvhLsw3bzjrYGmVkhbbkcuvGvOzY9SeALH2dMEGypZ/RF0EXZb+IU78liURz+qu3ysojU/CnVXS3hbeTmGB4/Kxnxd56qq4gfEvgoOQKgmDL/EdGcWHnRNHKTMk1SqfyZLH9FWKFf/N9XG58OCuw/J+4aV4=
  - secure: rmeDWkfvKGqEnZxNjyoIUB+TfPqFfduCYX31XC3sBsCnrpl+361O7z5R7rEaB4GNBCnJj77QApTq7gM1cz9llg1j7T1n6BwQC1/XEgsNdGofAiq1PLQOye6YegwRZs58M9aA3FV2Kf0p7OzI42YF/BIzoZXkTqGGHLU/TV+NI9lis7Ik/OGSWFcOFBF8v1liu6dP/egWDVicrXrMMhgLUC5JVvhhqP/L9ZQeBXgPt1na2gfCsX9BzKcNpluo4FyhZZwgrOHcFYyjfi2JQbL1PcwCFqO9YExcu2BetJ6jf4jVgNxkIUsxALQ9fjiIgyR3VE7iBKRsM7uf+98GHbBsE0JYWtpij3YTtccfyYxJyKDsOzJ0hjlyiHdzqbQVBtGwFqbJQGGxHdzS+WJ4FU11AWPqODYjGreecMs0BXYBjIjBiAHEBL79qnsq2QQmP1CtR+KwjAhO2uCzhg02kRrKPAaXFpBQTlrWUZXiM6eZuvHaq8ge/ZXjD5RMme9m4fLzr3FmISurbP7S6kIuIvr+zuL6cTq7XEEn6b+JQgoNUD/QJrZeG1sbes6mYTMr9qMlN+aW2JRg/DV5q14LrB8W6TBkUrmKdJB1zoowl9fe6+xhwSX59B24NncM+Qae/Ooq4LzToBu4UBdAW+uV8g04z13Fdj27en2uS5bmeb41C50=
language: node_js
node_js:
- 5.6
sudo: true
services:
- docker
before_install:
- sudo pip install awscli
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- npm install
before_script:
- export AUTH_UI_VERSION=`git describe  --tags --long || echo ${TRAVIS_COMMIT::12}`
- export AUTH_API_VERSION=0.1.1-11-ge884ca6
- echo "building $AUTH_UI_REPO:$AUTH_UI_VERSION"
- docker build -t $AUTH_UI_REPO:$AUTH_UI_VERSION .
- export HOST=localhost
- export PORT=$AUTH_UI_PORT
- export APIHOST=auth-api
- export APIPORT=$AUTH_API_PORT
- export RAILS_ENV=production
- export DB_HOST=db
- export DB_PORT=5432
- export DB_USER=postgres
- docker pull postgres:9.4
- docker run --name db -d postgres:9.4
- docker pull $AUTH_API_REPO:$AUTH_API_VERSION
- export SECRET_KEY_BASE=`docker run --rm $AUTH_API_REPO:$AUTH_API_VERSION bin/rake secret`
- docker run --rm --link=db -e RAILS_ENV -e DB_HOST -e DB_PORT -e DB_USER -e SECRET_KEY_BASE $AUTH_API_REPO:$AUTH_API_VERSION bin/rake db:setup
- docker run --name $APIHOST --link=db -e RAILS_ENV -e DB_HOST -e DB_PORT -e DB_USER -e SECRET_KEY_BASE -p $AUTH_API_PORT:$AUTH_API_PORT -d $AUTH_API_REPO:$AUTH_API_VERSION
- docker run --name auth-ui --link=$APIHOST -e HOST -e PORT -e APIHOST -e APIPORT -p $AUTH_UI_PORT:$AUTH_UI_PORT -d $AUTH_UI_REPO:$AUTH_UI_VERSION
- sleep 5
script:
- export APIHOST=localhost
- npm test
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker tag $AUTH_UI_REPO:$AUTH_UI_VERSION $AUTH_UI_REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $AUTH_UI_REPO
- export APP_VERSION=$AUTH_UI_VERSION
# - deploy/aws-eb/eb-deploy-update-env.bash
notifications:
  slack:
    rooms:
      secure: cAtWahPcfuejSd1SR/LVscP/2E3/zeFoqUfgheSBNoLyhz2R+cH2ez4raZABa7zEbRzZM7E9GklbokeUtEC9grx/MzKNBm3MurS826Y8ucv1F7zOZ/wNNTRKAObntR/Z8tl/oJVASeE6GLFG/H2fp8izEdtN7Mh8XsbLnCpwRBJd0gjwpaiSzEr1aO4MKXhF9jW5Q2mFUJ+nVUtWKmxbG4ceCerEP+cIx4ddw3L4JqPigdgZXD9PoUTV5JekkS7ZtgC+2lso5sJc47xo8kwjAaKxTy7x6RaNvd9oUzH1FdUvYOmZ7rTjD+iNN09cmkUqNWaL3QKGXN8f97qqYjzGgtVvlaY3235tAaf0CG4ZSrwjxWqTFPvEt2/S5bFqbdpNG3t9GISfi0l6hrojYvjnyIMk7+ZtuIrU5/3w6L4MzMg4oSTN/vfVT8L7BXDqtWqK/K7TRFdNmIhEdUkzF20aSZHuiChJvDYoQycQpvP+iiKXNrjtXMspEuBeUjNhHfuizOAd+yRnQdoaOfyKt9MCGqsveKFQJ55viFfH2C6nsZq9yz5fqCQWRfWz0JwQAs2Z5unRVcUFhgx4mvSLsiOVOoNYSrRqqIcM1chrVxfmvqQTHqzRHyZCJR6uOYeNGKHVEXWwUICshkgVgCEWXg8ov36TKU7mxPtfHl/VWBGrvyk=
