env:
  global:
    - secure: vkZZkhpHwQE+J9ZGiVsLjSLDhmVplczszXuiQqcZ7AO5tllu4gAC8ATW7FwwYm4N7/6jZ53m/QidfzhHoMOdik0/VeuK7PMZnx1ndl4WHc29pb7Jq0IOpLKNOItDsWcGfKV0JSW4uEJ1qS7PRPINE52ZmmN5+YMyVYzuUSxYS2vAWXmN8AVThrGpVXh+ezTuFmvzE69mEZFG1rlZqi0bt8OQjLmDu9J4toeidzxKJuuMcjlScs6cRZ9Ct1Z3wrRWrG/HdxS6lTynS5mjz1tAdxq57Q87jMjxHPH5pOsLDC/Wt/LfIbstWr1Sfs+p4YWcjUOnWkLIETw3hMEFD+BKNNjPLW9PTiUY0bLpVhz2MIFI6AlbPyAZ852QS0jgHz5geheq5S6ez59Ei2reW7qLG+j8SQSrmJpym0Gv/mhnhKs/h3ZIPNMdjEu2KHeXrbnC/p1HkWu/iwCiFU50rv5xsXAxFutdphKH9+teZZA/PuPaJnTUQ8w1xUtt+qVwGgIdUClMkR8JNicjAPNGOWGQiYQN6/mcloqnNcdgJL1hUlQW5W6Us/9CJVvpzsdRb8yCzpg/sv7nH2q8IEzzgtcECC1w6Kw8KhBv3f5psM943oJ1wsWw2j9jBNFrHDoGL7AhNNnuErzjzsFEnwXMwYN99zX4BefN1gtl8pp8vFkSGLs=
    - secure: EWCAKmIozdq+//OhbLGqO9LXq6eI+N76hJ3Lsb8tXOXuq8tqhscjzVYjqfJDWbpjoaZF6LK4lvkuOtobGXVjBNRrep9+HrX+ulTi7NtHm+6WVPq/K1d/QDeonUkD8C/V8daqsMne7Ie/qePEq6Q6CBlE/RAuWhCFMgcrlgvw2X1L8GkkycvNuwI+8uHAnvz4gfzBzCt8YbsdhUkCfSR/KaskYLxNfHh/kgAf0TRJztj3e0ez6iCWsnJr6utFeaSoa5uQjSjMXI7iK1CvLnCGCrUr/feX2ms7yG/jfMMacZfIAIX74DMXDOwZj+s4oQPq0U/f5zlkNotfC0YqR9YsCPG/bbzw4MP2FYZKsIXWTPnlRe7bzVHJfP5OhYEQBfJyJ0Fnl4P+ReLbl8UmVZunOyMbIolqXDYUgWKuS1znv47aVILpHZeduRhMA5reQ2kmr+ADIyNitDJOOzV3Qxhw/EhnKyjqTWj1JCBcIMBG105LlafAVc8dvrIU0BEVKI7Bhs+Qe4DT5aeEdMaWvG6FfxZHKaaSuofx3aJ1wttbcgfyYloKMe3v7vN1D2vvAJitXRlsxgxRckxi1XFSQWubYUNtBxqZHSJJHwTjtGdJMclLLla94j8X9dq/j3etAEFND3aIAiBSOKMDnd1kaqDl2AIackUDU3SPIdq4kEgVCZ8=
    - secure: BLwb9QHa//P2uYtcMgOAb6bNJ0Z6pSg6z8pDcZ4rYP1+n2dQmmo6dESsOaatZMPMdhQJrcDsIu69WdIxHzD5T8wRlpPw7NneALTJj1XYx9AwhHFy+0CwuuRHUplergNmHpXJo0sXvFGcvRgIj2DBsEN/yffuH1JsB8Z7LNdodyMotj6QX+2nMfpg+xqgNyCA/LqVuHWNiVHkqAlboD/Tsr1uSwp9fjPqJ8DYg9MF4L6RRmWoabtxPQAe3ZDpCDa+Wd4Mnw8uVde1Mk9fSTUE+Ors1TlXNcfCq+bkMMyqbtYk4P4CHQjWKCorjvBEzFLE8NrIdtm+ADTessLYIzhcfJ1YTFssd6NdBN5gvkWuk6FYcewAvhoSGxqUrxEre5N5tCHA2wAFgZgYkY+7k3ZTXoKO873zgeuXIaBlpUAF4Glc43flKvBrMAaBeGybX93im7wJWzLzpBfepTfB+d/QZM8N5NndBF/dQ2gs+Hlw6+LiolFim6Ep0h42uzte0QMngJMk5TMY8XrflDW7z7D5ZSVS6wAUQy9TCnSe9x6Sgz6U/fQ9CtKY8UZvNUTdKklugKfhyoE9EWnpjh/Wbd9OmZvFZV7oDmUHdFphmTTkDhUlDWOrRP/yE6jstk7FGwF/UqlG+auEz4LH+KvxXXprD7XPNDy1lVTfRCnkXK1L8J0=
    - secure: QjGc8K3/buHtFOW4c0/qPsAmroz+/kpd0yj3TRFPByzjgprKI6OaBkhfW5UoD8/yGEVT97KPLlcVyE9DpPx4fLuHKasAc3eDdlvOkaa8vaWQ5uP0KLARCWdyTVsx5V8WI9+Imwr+uHg+6waLrHSXvkAqFDQxyuoPKwk8Qm32x1B+QsbtLMoAMbE4gIKf3Hl63cuX2F9Hlvk27N9JsyVzH/n+NWdYuecL/X15L7XAnwB6epJWyL3wN/5oGV3j181kux3+nR50doUiOYnCrBrMx2Lkz5q5oeqER1mvZpxsQMQlqZKXRKcU83K8G9B/KZRCncroO4JM+0C3yBNS8+LgVRGiAS3/PxSsUfBblDgFk25AR3bdNvWmxOxRv9HeJZwL7fF82NsXfPWP3YZcyXVWCI63w0e+QqeWeGBL7mz4G6Ig0XDbtgx9slMdazajdAohbggm7jmvkP7sCTe4SXSPF6/onhkNb6KdjqQCeFnNNtwaTV6V56EGiPciM5lafQBNOW20QVmAG6CEcFR+dL9hDsVPhS1e5MD9y8M0ThA0Iub/lm0e96kumG/OBsSJrgnR+dVH/1tdixIkbBRVGwzykBZA55zseKWXf8MvYFCmXVOAgWMFkfgB6GCsTXlNHD1VhXSl++QfU39Rk7LZaoVnKxxuzYgk8+CvV0zmmsTZWQg=
    - secure: wginNC9PpjKLOtMtoZH4Cs8RLlNASktZJHU/BP53n4lPQyEaVjzyTcPLtGC7lMuEACBiegjW+7Rx6a1vOoTQiysCZthkojd5wnaRGASE0laVvgwlqhDAjAkeSnfWc5t6xBtSL9UZsc68z4UApzS+b2sivnps44wltZCKMZ55FDV9H8GO3h9nDKdfF3jnCVXAEGI7+38w4coelQlKvDDFTWJmejbfyCf7gCglwWHrLDt0D2Ca7V+W1NPSnTN/hXXzV/kykl59LL8YqbfFwKySpaTP5UJpT2+S+1S2wWGF8jm0UaHmHirNtBwSRhf7RflWwDeNRu3gohJp6iTO7HjIJrfHqKuzfdM7VBfz8nYRnr/qPob55ChRLyZ4s2VYYFYyzYJfcf/LOi9zgK36EWFnpAPMUpA3mWmi2oMCOUggFCvTp6KwXqoxMbbPOiP8kBS/N2xkywpmlwtHmTRhBagviGG+rIjgE1szU6f1nPIjNRZmXdFW34UA3Jz373QXZHBszMd6D/h8tskVeU0Nkggj/qZmyqqPpOLGX++vwaX1mBe6JHYKa4qvjsg/FDSdV65sxGNDUyzFqQjG/7HZSQMI2KdMQJrBKNpwoJoCyDYAidZsGRByRU/4JecUgjsgRM5QO/8WAiTtex4eT2jyUskcAb8nKUJRgTizPj2of43Ss/Y=
    - AWS_DEFAULT_REGION=ap-northeast-1
    - AWS_VPC_ID=vpc-4d790e28
    - APP_NAME=parti-auth
    - APP_ENV_NAME=parti-auth-pr
    - APP_S3BUCKET=parti-auth
    - APP_IAM_ROLE=arn:aws:iam::453285904053:instance-profile/aws-elasticbeanstalk-ec2-role
    - APP_KEY_PAIR=parti-tokyo
    - APP_SECURITY_GROUPS=ec2-parti-auth
    - DOCKER_REPO=partixyz/auth-ui
    - AUTH_UI_PORT=8080

language: node_js

node_js:
  - 5.6

sudo: true

services:
  - docker

before_install:
  - sudo pip install awscli

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

before_script:
  - export APP_VERSION=`git describe  --tags --long || echo ${TRAVIS_COMMIT::12}`
  - docker build -t $DOCKER_REPO:$APP_VERSION .
  - docker run -d -p $AUTH_UI_PORT:8080 $DOCKER_REPO:$APP_VERSION
  - sleep 5

script:
  - npm run test-e2e

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $DOCKER_REPO:$APP_VERSION $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO
  - deploy/aws-eb/eb-deploy-update-env.bash
