env:
  global:
    - AUTH_UI_REPO=partixyz/auth-ui
    - USERS_API_PORT=3031
    - secure: Xee1vuhmqzpTJMDGpZijOeMKE5NGNcskI9j10dv6vFp9oTjtyhEprpbuwEsc9bZ0TXoT9bpiEZUxX3eAWomTvM4OefVLVU34TPzZ7+5a5XBJc5IlnsiY4RqT+SAkqxHjrFcWlts1LyrkiS3mt+e5BQ+wMCKt+DbEmZ//PT/McTkAUatRE5clQqKJW3wQk8cP4GGbjtJeelpkjejb6fPwqAIPN3mnkmMOIUtvPi5BRh6zdaamQeLHtB3KAu+EjOObpJ+xNasGirZ6ijARrMZXfD7LKgxLX4wSMNXsV1MHW8+cOtZRBThk4vXBcQ6GuY2NGf0PoRbe/n01hmP/3T3MiTcUC+ZLyDMKkpc+KVaARfc4UC2WtyWgLOPIxOeNyVIXwNBFbnYOncCQzHweJe2YmgYD0q1DlpEUEMrS87NCfKS31YyhNivOsrBgt3AQBPTA1nc+k4vgcWqywY8/JZqwIyfQX9nOJJYUL8cdg/QkfL2vsCrHCcME3YgvsbJFgo+JL6DCYzjSpqZz3LYxrfhlU0vBph7W9wepW3VfNs6vQfva/cdYR8iUg32VC0ncQfV6+gbEI4fIXfmOVtEV8nvTAjryyIC7+eQIOBfwsqVrPDUxuJNHEODXeWtXpq6UR7huWK272YqpJ0msyfz17OyxP2BeAUc4YDSTnE0JA2pjHeg=

language: node_js

node_js:
  - 5.6

sudo: required

services:
  - docker

addons:
  hosts:
    - auth-api
    - users-api

before_install:
  - sudo service postgresql stop
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - sudo apt-get -y install python-pip
  - sudo pip install docker-compose
  - docker -v
  - docker --help
  - docker-compose -v
  - echo $NODE_ENV

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

before_script:
  - openssl aes-256-cbc -d -k $secret -in .env.enc -a -out .env
  - source .env; rm -f .env

script:
  - ./deploy/docker-compose-up-test.bash
  - npm run test-node

  - export APP_VERSION=`git describe  --tags --long || echo ${TRAVIS_COMMIT::12}`
  - echo "building $AUTH_UI_REPO:$APP_VERSION"
  - ./deploy/build-docker-image.bash
  - AUTH_API_CONTAINER=$( docker-compose -f deploy/docker-compose-test.yml ps -q auth-api )
  - docker attach --sig-proxy=false $AUTH_API_CONTAINER | sed -e 's/^/AUTH /' &
  - docker exec -i $AUTH_API_CONTAINER sh -c "tail -f log/test.log | sed -e 's/^/AUTH-LOG /'" &
  - USERS_API_CONTAINER=$( docker-compose -f deploy/docker-compose-test.yml ps -q users-api )
  - docker attach --sig-proxy=false $USERS_API_CONTAINER | sed -e 's/^/USERS /' &
  - docker exec -i $USERS_API_CONTAINER sh -c "tail -f log/test.log | sed -e 's/^/USERS-LOG /'" &
  - docker-compose -f deploy/docker-compose-test.yml up auth-ui &
  - sleep 3
  - docker-compose -f deploy/docker-compose-test.yml ps
  - npm run test-e2e

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $AUTH_UI_REPO:$APP_VERSION
