env:
  global:
  - AWS_DEFAULT_REGION=ap-northeast-1
  - AWS_VPC_ID=vpc-4d790e28
  - APP_NAME=parti-auth
  - APP_ENV_NAME=parti-auth-pr
  - APP_S3BUCKET=parti-auth
  - APP_IAM_ROLE=arn:aws:iam::453285904053:instance-profile/aws-elasticbeanstalk-ec2-role
  - APP_KEY_PAIR=parti-tokyo
  - APP_SECURITY_GROUPS=ec2-parti-auth
  - DOCKER_REPO=partixyz/auth-ui
  - AUTH_UI_PORT=8080
  - secure: WlG4s1tyIx9mE8HrMGpUdsWAXAWCw5rMyiD+23IV0xipKgErGCxD7JJFbpNU83AoSzZIfdcDPGji0aQyY04J7JYNP39k6EgUMBT8KKfKzDncIepxKGufYQJixf0RAAnFtrhoJRnzJNpvyWWZBfK8grMWngcx/CjfjhWhPw7REo5u4e/XlDL3WzCghq7bntAiiooHNimATz4VhsI7l0dY6IpayKxEG0hV8Fwx3b6TP0gmqGunMpFGfm5TbVyayCrq/xY/1JU0zv71eSwo+fQpZkuFkbtpJDB5eFYaPWtoZk/Y+4h5Eq9W2d+S9qbUMxBVMrqxYoiJkbWnJGmZmZ8W19AMPC+leTuS4G1Kcdf0sezOrE7X8SdarPuOswQOt3rafgCfWJLYJ/DflqOCCHMt5j22ABm4QmCCniE8F2VdtkApqzDE/PVHLJ5jOBdspk0rVI+3CO3sRGKlvbKndMK1dW4zGI5An31ucg9oMNapGhemds1cY6ZM/LirUUkY7l3OdhHYMP+OYP0SWQDuC7ZOXZ5SlGkxAWGNqQfj2CgIMd0+TF0APRPkGieb5klIuz/nGXO7Bx1dWuV0Qu88Gb/y8bB++xn4JlLOMVVYH6M2ZsTjbPkh81PLIgwgcUFw4SCzywN0Kzh0GNoH9+E15pWc9L3u0K0uKU7kdehmB/gismU=
  - secure: ZKhl4v+1jXDhtoIUifcNAm4z7FDQuu1yWRLcGV/vHPMaXZDHIe/5td5iJ0OfzjzwHFHf+RQJ0MHxuksUmVKI7ZRU+80LL6paFLfmqiNnVKhCPmTjDLuZOjp0P4hLW8p3fliObGP40sZQzL6FUiwHN9Bv51x7purWw35o4NDOohg9ugm4txCG+dzfKq8CfZKTAU8+In9fwaFc2scwqEMTzG9YEQXOddrLgE0vHZBQ4XM7xCyjk5E8DkUGnFqw13fJHMHNh1fInB7q8qcxGySeLievKG0pTEvf+6zXx9OyWK/3zQlBpdzD1PdgW+ZAE30HqglHb/65wHpucf8d76xyXkxyRMFvTSXKgrV0q39F4x067HtHt7XFZGJ/VowjUwCy9FlODDHa9bWRem9sXQ9fRpBR37mbRn+Rldkwy2LF85qMcnjORj6hc5YKLbikFUn6AoLGAO1lhdUBABvurp1+SJNsaks5l2ExslHcj7Hk+rPfNwU3YWuxmqQzgYPsnYXIQAWl3rjBgrRlMedo+/7YZa0rtCjdvK1jYs4Z0vK7gFtJynKMPVrfqWjO6rr8QQzklmkKLnhsmKJGNXKobk/ver7RBgquGLszt4/tmxBNj/kTepBEOjbrpXSaKhKVBw6gj8nBD+b79URcJ5UgWhdkXAbVkU8qvBj6jIYPm6U22co=

language: node_js

node_js:
  - 5.6

sudo: true

services:
  - docker

before_install:
  - sudo pip install awscli

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

before_script:
  - export APP_VERSION=`git describe  --tags --long || echo ${TRAVIS_COMMIT::12}`
  - docker build -t $DOCKER_REPO:$APP_VERSION .
  - docker run -d -p $AUTH_UI_PORT:8080 $DOCKER_REPO:$APP_VERSION
  - sleep 5

script:
  - npm run test-e2e

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $DOCKER_REPO:$APP_VERSION $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO
  - deploy/aws-eb/eb-deploy-update-env.bash
