#!/usr/bin/env bash

script_dir() {
    local source="${BASH_SOURCE[0]}"
    while [ -h "$source" ] ; do # resolve $SOURCE until the file is no longer a symlink
        local dir="$( cd -P "$( dirname "$source" )" && pwd )"
        source="$( readlink "$source" )";
        # if $source was a relative symlink
        # we need to resolve it relative to the path where the symlink file was located
        [[ $source != /* ]] && source="$dir/$source"
    done
    printf "$( cd -P "$( dirname "$source" )" && pwd )"
}

SCRIPT_DIR=$( script_dir )
ROOT_DIR=$( dirname $SCRIPT_DIR )

COMPOSE_FILE=${ROOT_DIR}/deploy/docker-compose-test.yml
AUTH_API_IMAGE_NAME=auth-api

AUTH_API_CONTAINER=$( docker-compose -f $COMPOSE_FILE ps -q $AUTH_API_IMAGE_NAME )

docker attach --sig-proxy=false $AUTH_API_CONTAINER
