auth-api:
  environment:
    - DB_USER=postgres
    - RAILS_ENV=test
    - USERS_API_HOST
  image: partixyz/auth-api:0.3.1-6-g8c5615b
  links:
    - db:auth-db
  ports:
    - 3030:3030
auth-ui:
  environment:
    - APIHOST=auth-api
    - RAILS_ENV=test
  image: partixyz/auth-ui:current
  links:
    - auth-api
    - users-api
  ports:
    - 8080:8080
db:
  image: postgres:9.4
  ports:
    - 5432:5432
users-api:
  environment:
    - DB_USER=postgres
    - RAILS_ENV=test
  image: partixyz/users-api:0.2.0-5-g7fd4373
  links:
    - auth-api
    - db:users-db
  ports:
    - 3031:3030
