auth-api:
  environment:
    - AUTH_API_CERTIFICATE_BASE64
    - AUTH_API_EXTERNAL_HOST
    - AUTH_API_EXTERNAL_PORT
    - AUTH_API_PRIVATE_KEY_BASE64_1
    - AUTH_API_PRIVATE_KEY_BASE64_2
    - AUTH_API_PRIVATE_KEY_PASS_PHRASE
    - AUTHORIZATION_ENDPOINT
    - DB_USER=postgres
    - RAILS_ENV
    - RAILS_LOG_TO_STDOUT=true
    - SECRET_KEY_BASE
  image: partixyz/auth-api:0.3.1-21-gd7f11f4
  links:
    - db:auth-db
  ports:
    - 3030:3030
auth-ui:
  environment:
    - APIHOST=auth-api
    - AUTH_UI_CLIENT_ID
    - AUTH_UI_CLIENT_SECRET
  image: partixyz/auth-ui:current
  links:
    - auth-api
    - users-api
  ports:
    - 8080:8080
db:
  image: postgres:9.4
  ports:
    - 5432:5432
users-api:
  environment:
    - DB_USER=postgres
    - RAILS_ENV
    - RAILS_LOG_TO_STDOUT=true
    - SECRET_KEY_BASE
    - USERS_API_CLIENT_ID
    - USERS_API_CLIENT_SECRET
  image: partixyz/users-api:0.2.0-14-g2baefb1
  links:
    - auth-api
    - db:users-db
  ports:
    - 3031:3030
